version: '3.1'
services:
    mongodb:
            image: mongo:latest
            ports:
                - 27017:27017
    mongotimestamp:
            image: mongotimestamp:latest
#            environment:
#                - JAVA_OPTS=p
            depends_on:
                - mongodb